### ISSUE TITLE
Exception thrown: 'Microsoft.ProjectOxford.Face.FaceAPIException' in System.Private.CoreLib.ni.dll

### ISSUE THREAD

**Issue by edacostacegb** [shijiong/RPiCognitiveService#1]
Hello

First, I want to thank you for your code.
I have a question about this code because the error described in the title occurs.

Where do you define the endpoint for the face API and the CV API

Regards

Emmanuel

**Comment by shijiong** [comment]
Hello, friend.
Sorry for the delayed reply. You can add service endpoint as follows for FaceAPI,

FaceServiceClient f_client = new FaceServiceClient(key_face, "https://westcentralus.api.cognitive.microsoft.com/face/v1.0");

**Comment by shijiong** [comment]
I believe it is quite simple for you to add this endpoint for Computer Vision API.

**Comment by edacostacegb** [comment]
Hello

Thank you for the help.

I was able to use the application you built.

Regards

Emmanuel

**Comment by shijiong** [comment]
Great!
It's good to hear the successful news.
